server:
  port: 8081

kafka:
  url: http://localhost:29092

cloud:
  aws:
    credentials:
      access-key: 
      secret-key: 
    s3:
      bucket: 
    region:
      static: 
    stack:
      auto: false


eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka


spring:
  application:
    name: catalog-service

  config:    
    import: optional:configserver:http://localhost:8888

  datasource:
    url: jdbc:mysql://localhost:3306/productdb
    username: 
    password: 
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        dialect : org.hibernate.dialect.MySQLDialect

  data:
     redis:        
          lettuce:
            pool:
              max-active: 5
              max-idle: 5
              min-idle: 2  
          host: localhost
          port: 6379
          password: 

logging:
    level:      
        org:
          springframework : debug
      

        
 


