server:
    port: 8080

frontend:
    url: http://www.ysyproject.com

feign:
    catalog-url: http://localhost:8081
        

kafka:
  url: http://mywebserv.site:29092

cloud:
  aws:
    credentials:
      access-key: AKIAYS2NW7K5A2SDATN2
      secret-key: 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
    s3:
      bucket: webboy-dev
    region:
      static: ap-northeast-2
    stack:
      auto: false



 
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka


spring:
    application:
        name: user-service

    config:
      import: "optional:configserver:http://localhost:8888"

    datasource:
       url: jdbc:mysql://mywebserv.site:3306/userdb?serverTimezone=Asia/Seoul
       username: admin
       password: ysY2273!
    jpa:
        show-sql: false
        hibernate:
            ddl-auto: none
        properties:
             hibernate:
                 format_sql: true
                 #use_sql_comments: true
                 #type: trace
                 dialect : org.hibernate.dialect.MySQLDialect

                 

    data:
      redis:        
          lettuce:
            pool:
              max-active: 5
              max-idle: 5
              min-idle: 2  
          host: mywebserv.site
          port: 6379
          password: ysY2273!

    app:
       jwtCookieName: user-cookie
       jwtRefreshCookieName: user-refresh-cookie
       jwtSecret: "mySecretKey123912738aopsgjnspkmndfsopkvajoirjg94gf2opfng2moknm"
       jwtExpirationMs: 7200000
       jwtRefreshExpirationMs: 1209600000

    mail: 
      host: smtp.gmail.com
      port: 587
      username: Sangyong79@gmail.com
      password: qfpp cubv ieio rodd
      properties:
        mail:
          smtp:
            auth: true
            starttls:
               enable: true

    security:
       oauth2:
         client:
           registration:
                google:
                   client-id: 1015215671564-2l317hkb9l48r3fflfvr0eucto00ik88.apps.googleusercontent.com
                   client-secret: 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
    

logging:
    level:
      root : info
        
                
                



