server:
    port: 8080

frontend:
    url: http://localhost:3000

kafka:
  url: http://localhost:29092

cloud:
  aws:
    credentials:
      access-key: 
      secret-key: 
    s3:
      bucket: 
    region:
      static: 
    stack:
      auto: false

feign:
    catalog-url: http://localhost:8081

 
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka


spring:
    application:
        name: user-service

    config:
      import: "optional:configserver:http://localhost:8888"

    datasource:
       url: jdbc:mysql://localhost:3306/userdb?serverTimezone=Asia/Seoul
       username: 
       password: 
    jpa:
        show-sql: false
        hibernate:
            ddl-auto: update
        properties:
             hibernate:
                 format_sql: true
                 #use_sql_comments: true
                 #type: trace
                 dialect : org.hibernate.dialect.MySQLDialect

                 

    data:
      redis:        
          lettuce:
            pool:
              max-active: 5
              max-idle: 5
              min-idle: 2  
          host: localhost
          port: 6379
          password: 

    app:
       jwtCookieName: user-cookie
       jwtRefreshCookieName: user-refresh-cookie
       jwtSecret: 
       jwtExpirationMs: 108000
       jwtRefreshExpirationMs: 5184000

    mail: 
      host: smtp.gmail.com
      port: 587
      username: 
      password: 
      properties:
        mail:
          smtp:
            auth: true
            starttls:
               enable: true

    security:
       oauth2:
         client:
           registration:
                google:
                   client-id: 
                   client-secret: 
    

logging:
    level:
      #root : info
      org:
       springframework : debug
        
                
                



