server:
  port: 8084

kafka:
  url: http://mywebserv.site:29092

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://57.182.208.121:8761/eureka

feign:
  user-url: http://57.182.208.121:8080
  catalog-url: http://57.182.208.121:8081
  cart-url: http://localhost:8082

spring:
  application:
    name: order-service

  config:
     import: "optional:configserver:http://57.182.208.121:8888"

  datasource:
    url: jdbc:mysql://mywebserv.site:3306/orderdb?serverTimezone=Asia/Seoul
    username: admin
    password: ysY2273!
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        dialect : org.hibernate.dialect.MySQLDialect

logging:
    level:
      root : info
        

    
        
        
