server:
  port: 8087

kafka:
  url: http://localhost:29092

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka


spring:
  application:
    name: pay-service

  config:
     import: "optional:configserver:http://localhost:8888"

  datasource:
    url: jdbc:mysql://localhost:3306/paydb?serverTimezone=Asia/Seoul
    username: admin
    password: ysY2273!
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect : org.hibernate.dialect.MySQLDialect

  data:
      redis:        
          lettuce:
            pool:
              max-active: 5
              max-idle: 5
              min-idle: 2  
          host: localhost
          port: 6379
          password: ysY2273!

logging:
  level:
    org:
      springframework:
        security: DEBUG
