server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ruke79/config.git
          search-paths: config-file/**
          basedir: ./repo
          default-label: main
          ignoreLocalSshSettings: true
          strictHostKeyChecking: false
          hostKey: github.com ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBEmKSENjQEezOmxkZMy7opKgwFB9nkt5YRrYMjNuG5N87uRgg6CLrbo5wAdT/y6v0mKV0U2w0WZ2YB/++Tpockg=
          hostKeyAlgorithm: ecdsa-sha2-nistp256
          privateKey: |            
            ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBJRmBAMauQAj4xEctcqiog3gXEnXhoK+hzTFE7Jeow5EohXPhFVslm9zVZn0rd7uj3z0oFPfFDd18AkbTrP7C2U= u2you@DESKTOP-EJEJQKM

  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
            
management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, http, busrefresh, info, metrics, prometheus