server:
  port: 8086

kafka:
    url: http://mywebserv.site:29092


eureka:
    instance:
      prefer-ip-address: true
      instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    client:
      register-with-eureka: true
      fetch-registry: true
      service-url:
        defaultZone: http://localhost:8761/eureka

feign:
  user-url: http://localhost:8080
    

spring:
    application:
      name: chat-service

    config:
      import: "optional:configserver:http://localhost.site:8888"

       

    datasource:
      url: jdbc:mysql://mywebserv.site:3306/chatdb?serverTimezone=Asia/Seoul
      username: admin
      password: ysY2273!

    jpa:
      hibernate:
         ddl-auto: none

    data:
      mongodb:
        client: mongodb://admin:ysY2273!@mywebserv.site:27017
        name: chat
        username: admin
        password: ysY2273!
        auto-index-creation: true
      redis:
        repositories:
          enabled: false
        lettuce:
          pool:
            max-active: 5
            max-idle: 5
            min-idle: 2  
        host: mywebserv.site
        port: 6379
        password: ysY2273!

    app:    
      jwtSecret: mySecretKey123912738aopsgjnspkmndfsopkvajoirjg94gf2opfng2moknm

logging:
    level:
      root : info
        

