server:
  port: 8086

kafka:
    url: 


eureka:
    instance:
      prefer-ip-address: true
      instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    client:
      register-with-eureka: true
      fetch-registry: true
      service-url:
        defaultZone: http://:8761/eureka

feign:
  user-url: http://:8080
    

spring:
    application:
      name: chat-service

    config:
      import: "optional:configserver:http://:8888"

       

    datasource:
      url: jdbc:mysql://3306/chatdb
      username: 
      password: 

    jpa:
      hibernate:
         ddl-auto: none

    data:
      mongodb:
        client: mongodb://:27017
        name: chat
        username: 
        password: 
        auto-index-creation: true
      redis:
        repositories:
          enabled: false
        lettuce:
          pool:
            max-active: 5
            max-idle: 5
            min-idle: 2  
        host: 
        port: 6379
        password: 

    app:    
      jwtSecret: 

logging:
    level:
      root : info
        
 
